"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
type Level = 0 | 1 | 2;
type Card = { id: string; question: string; answer: string; notes: string; source: string; dueDate: string; level: Level; lastReviewed?: string };
type State = { intervals: number[]; cards: Card[] };
const defaults: State = { intervals: [0, 1, 3, 7, 30], cards: [] };
const choices = [0, 1, 3, 7, 30];
const label = (n: number) => n === 0 ? "当日" : n === 1 ? "翌日" : n === 3 ? "3日後" : n === 7 ? "1週間後" : "1か月後";
const date = (offset = 0) => { const d = new Date(); d.setDate(d.getDate() + offset); return d.toISOString().slice(0, 10); };
function normalize(value: unknown): State { if (!value || typeof value !== "object") return defaults; const v = value as Partial<State>; return { intervals: Array.isArray(v.intervals) && v.intervals.length ? v.intervals.filter((x): x is number => typeof x === "number").sort((a, b) => a - b) : defaults.intervals, cards: Array.isArray(v.cards) ? v.cards.filter((x): x is Card => Boolean(x) && typeof x.id === "string").map((x) => ({ ...x, answer: x.answer || "", notes: x.notes || "", source: x.source || "", dueDate: x.dueDate || date(), level: x.level === 1 || x.level === 2 ? x.level : 0 })) : [] }; }
function save(value: State) { return fetch("/api/study", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value), keepalive: true }).catch(() => undefined); }
export default function StudyClient({ initialValue }: { initialValue: unknown }) {
  const [state, setState] = useState(() => normalize(initialValue)); const [tab, setTab] = useState<"review" | "add" | "settings">("review"); const [revealed, setRevealed] = useState(false); const mounted = useRef(false);
  const due = useMemo(() => state.cards.filter((c) => c.dueDate <= date() && c.lastReviewed !== date()), [state.cards]); const card = due[0];
  useEffect(() => { if (!mounted.current) { mounted.current = true; return; } void save(state); }, [state]);
  const review = (level: Level) => { if (!card) return; const i = state.intervals[level === 0 ? 0 : level === 1 ? Math.floor((state.intervals.length - 1) / 2) : state.intervals.length - 1] ?? 1; setState((s) => ({ ...s, cards: s.cards.map((c) => c.id === card.id ? { ...c, level, dueDate: date(i), lastReviewed: date() } : c) })); setRevealed(false); };
  const add = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const question = String(f.get("question") || "").trim(); if (!question) return; setState((s) => ({ ...s, cards: [...s.cards, { id: `study-${Date.now()}`, question, answer: String(f.get("answer") || ""), notes: String(f.get("notes") || ""), source: String(f.get("source") || ""), dueDate: date(), level: 0 }] })); e.currentTarget.reset(); setTab("review"); };
  return <main className="studyShell"><header><div><p>公認会計士</p><h1>学習モード</h1></div><strong>今日の復習 {due.length}件</strong></header><div className="tabList studyTabs"><button className={tab === "review" ? "tabButton active" : "tabButton"} onClick={() => setTab("review")}>復習</button><button className={tab === "add" ? "tabButton active" : "tabButton"} onClick={() => setTab("add")}>問題を追加</button><button className={tab === "settings" ? "tabButton active" : "tabButton"} onClick={() => setTab("settings")}>設定</button></div>{tab === "review" && <section className="studyCard">{card ? <><span>問題</span><h2>{card.question}</h2>{revealed ? <><div className="studyAnswer"><h3>解答・要点</h3><p>{card.answer || "未入力"}</p><h3>解き方・注意点</h3><p>{card.notes || "未入力"}</p></div><div className="studyLevelButtons"><button onClick={() => review(0)}>要復習</button><button onClick={() => review(1)}>理解中</button><button onClick={() => review(2)}>定着</button></div></> : <button className="studyReveal" onClick={() => setRevealed(true)}>答えを確認する</button>}</> : <p className="emptyText">今日の復習はありません。</p>}</section>}{tab === "add" && <form className="studyCard studyAddForm" onSubmit={add}><label>問題・論点名<input name="question" required /></label><label>解答・要点<textarea name="answer" /></label><label>解き方・注意点<textarea name="notes" /></label><label>教材・問題番号<input name="source" /></label><button>追加して今日復習する</button></form>}{tab === "settings" && <section className="studyCard"><h2>復習の頻度</h2><div className="studyIntervalList">{choices.map((n) => <label key={n}><input type="checkbox" checked={state.intervals.includes(n)} disabled={state.intervals.length === 1 && state.intervals.includes(n)} onChange={() => setState((s) => ({ ...s, intervals: s.intervals.includes(n) ? s.intervals.filter((x) => x !== n) : [...s.intervals, n].sort((a, b) => a - b) }))} />{label(n)}</label>)}</div></section>}</main>;
}
